[package]
name = "sui-bridge"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
ethers = "2.0.13"
tokio = { workspace = true, features = ["full"] }
sui-types.workspace = true
sui-common.workspace = true
arc-swap.workspace = true
num_enum.workspace = true
move-core-types.workspace = true
url.workspace = true
futures.workspace = true
once_cell.workspace = true
telemetry-subscribers.workspace = true
prometheus.workspace = true
async-trait.workspace = true
typed-store-derive.workspace = true
rocksdb.workspace = true
typed-store.workspace = true
mysten-metrics.workspace = true
sui-sdk.workspace = true
sui-config.workspace = true
clap.workspace = true
tracing.workspace = true
git-version.workspace = true
const-str.workspace = true
bcs.workspace = true
sui-json-rpc-types.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
eyre.workspace = true
tempfile.workspace = true
axum.workspace = true
anyhow.workspace = true
reqwest.workspace = true
fastcrypto.workspace = true
tap.workspace = true
rand.workspace = true
lru.workspace = true
shared-crypto.workspace = true
backoff = { version = "0.4.0", features = [
  "futures",
] }

[dev-dependencies]
sui-types = { workspace = true, features = ["test-utils"] }
sui-json-rpc-types = { workspace = true, features = ["test-utils"] }
sui-config.workspace = true
sui-test-transaction-builder.workspace = true
test-cluster.workspace = true
hex-literal = "0.3.4"


[build-dependencies]
forge = { git = "https://github.com/foundry-rs/foundry.git", rev = "3dfa43bf1fa030a6c76c36a12feb4f2fe623b89b", package = "forge"}

[[bin]]
name = "sui-bridge-cli"
path = "src/tools/cli.rs"
